services:
  - type: web
    name: arvind-portfolio
    env: python
    buildCommand: pip install -r chatbot/requirements.txt
    startCommand: cd chatbot && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
